AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  LF1Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index-photos.lambda_handler
      Runtime: python3.9
      CodeUri: ./Lambdas/
      Role: "arn:aws:iam::290851490523:role/service-role/index-photos-role-uhv2ehqp"
      Timeout: 30
      MemorySize: 128
  LF2Function:
    Type: AWS::Serverless::Function
    Properties:
      Handler: search-photos.lambda_handler
      Runtime: python3.9
      CodeUri: ./Lambdas/
      Role: "arn:aws:iam::290851490523:role/service-role/search-photos-role-ghk40dy2"
      Timeout: 30
      MemorySize: 128